version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: user-service-app
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        networks:
            - user-service-network

    db:
        image: postgres:15
        container_name: user-service-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: user_service
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - user-service-network

    redis:
        image: redis:7-alpine
        container_name: user-service-redis
        ports:
            - "6379:6379"
        networks:
            - user-service-network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: user-service-rabbitmq
        ports:
            - "5672:5672" # AMQP protocol port
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - user-service-network

networks:
    user-service-network:
        driver: bridge

volumes:
    postgres_data:
